version: 2
updates:
  - package-ecosystem: npm
    directory: /creatorflow
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      capacitor:
        patterns:
          - "@capacitor/*"
          - "@capacitor-community/*"
      dev-dependencies:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /google-app
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      capacitor:
        patterns:
          - "@capacitor/*"
      dev-dependencies:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
